<a href="https://colab.research.google.com/github/premkumar205/deeplearning-pjt/blob/main/RNN_practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN,Dense,Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [ ]:
# sample dataset
data={
    'text':[
        "i love this cinema",
        "this cinema was rampage",
        "amazing acting and story",
        "i hate this cinema",
        "best cinema ever",
        "worst movie ever",
        "Really good cinema",
        "great cinema",
        "not good cinema",
    ],
    'sentiment':[1,0,1,0,1,0,1,1,0]
}

In [ ]:
# convert dictionary into dataframe
df=pd.DataFrame(data)
df

                       text  sentiment
0        i love this cinema          1
1   this cinema was rampage          0
2  amazing acting and story          1
3        i hate this cinema          0
4          best cinema ever          1
5          worst movie ever          0
6        Really good cinema          1
7              great cinema          1
8           not good cinema          0

                       text  sentiment
0        i love this cinema          1
1   this cinema was rampage          0
2  amazing acting and story          1
3        i hate this cinema          0
4          best cinema ever          1
5          worst movie ever          0
6        Really good cinema          1
7              great cinema          1
8           not good cinema          0

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(num_words=1000)
tokenizer.fit_on_texts(df['text'])
sequences=tokenizer.texts_to_sequences(df['text'])

In [ ]:
sequences

[[3, 6, 2, 1],
 [2, 1, 7, 8],
 [9, 10, 11, 12],
 [3, 13, 2, 1],
 [14, 1, 4],
 [15, 16, 4],
 [17, 5, 1],
 [18, 1],
 [19, 5, 1]]

In [ ]:
#padding
X=pad_sequences(sequences,maxlen=5)
y=df['sentiment']

In [ ]:
X

array([[ 0,  3,  6,  2,  1],
       [ 0,  2,  1,  7,  8],
       [ 0,  9, 10, 11, 12],
       [ 0,  3, 13,  2,  1],
       [ 0,  0, 14,  1,  4],
       [ 0,  0, 15, 16,  4],
       [ 0,  0, 17,  5,  1],
       [ 0,  0,  0, 18,  1],
       [ 0,  0, 19,  5,  1]], dtype=int32)

In [ ]:
#split data into train and test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
## RNN Model
model=Sequential()

model.add(Embedding(input_dim=1000,output_dim=32,input_length=5))
model.add(SimpleRNN(32))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
# compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
# train model
model.fit(X_train,y_train,epochs=10,batch_size=2)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 261ms/step - accuracy: 0.5714 - loss: 0.6920
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7143 - loss: 0.6583
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7143 - loss: 0.6425
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8571 - loss: 0.6205
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8571 - loss: 0.6045
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5781
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.5515
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.5214
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.4886
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.4504

In [ ]:
loss,accuracy=model.evaluate(X_test,y_test)
print(f"loss:{loss}")
print(f"accuracy:{accuracy}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 513ms/step - accuracy: 0.0000e+00 - loss: 0.8656
loss:0.8656349182128906
accuracy:0.0

# *Twitter Review on sentiment analysis using RNN:*

- twitter scraping using snscraps

In [ ]:
!pip install snscrape

Collecting snscrape
  Downloading snscrape-0.7.0.20230622-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from snscrape) (2.32.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from snscrape) (6.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from snscrape) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from snscrape) (3.25.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape) (1.7.1)
Downloading snscrape-0.7.0.20230622-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 5.5 MB/s eta 0:00:00
Installing collected packages: snscrape
Successfully installed snscrape-0.7.0.20230622

In [ ]:
df=pd.read_csv('tweets.csv')
df.head()

/tmp/ipykernel_1348/2588502539.py:1: DtypeWarning: Columns (5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('tweets.csv')

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source
0,Auesha Sumayaa,NaN,Passionate #learner and curious observer | #Tw...,2020-01-21 05:14:40+00:00,1724.0,548.0,3224,False,2023-06-10 08:57:07+00:00,The spirit of democracy and freedom is alive i...,['Zahedan'],Twitter for iPhone
1,Darius Bianchi 🇨🇦 🇮🇹,NaN,"Politics, Historiography, Sociology\n#Resistin...",2020-12-01 17:02:30+00:00,2260.0,1983.0,11789,False,2023-06-10 08:47:34+00:00,@HappyHippieRes @SARA2001NOOR @oprman @knrepp ...,NaN,Twitter Web App
2,Gabriella Julia,NaN,#Advocate for #education and promoting inclusi...,2020-12-30 07:45:41+00:00,1192.0,374.0,1304,False,2023-06-10 08:47:05+00:00,The determination of the protestors in #Zaheda...,['Zahedan'],Twitter for iPhone
3,𝐈𝐫𝐚𝐧𝐢𝐚𝐧 𝐯𝐨𝐢𝐜𝐞,NaN,The struggle for freedom and democracy\nhttps:...,2017-03-12 11:10:22+00:00,3381.0,2267.0,30162,False,2023-06-10 08:26:14+00:00,Protests and attacks against Iran’s regime con...,"['Iran', 'IranProtests', 'IranUprising']",Twitter Web App
4,𝐈𝐫𝐚𝐧𝐢𝐚𝐧 𝐯𝐨𝐢𝐜𝐞,NaN,The struggle for freedom and democracy\nhttps:...,2017-03-12 11:10:22+00:00,3381.0,2267.0,30162,False,2023-06-10 08:26:02+00:00,Brave Baluchis renew Iran’s anti-regime protes...,"['Iran', 'IranProtests', 'IranUprising']",Twitter Web App

In [ ]:
# Uninstall broken version
!pip uninstall snscrape -y

# Install community-patched version compatible with Python 3.12
!pip install git+https://github.com/JustAnotherArchivist/snscrape.git

Found existing installation: snscrape 0.7.0.20230622
Uninstalling snscrape-0.7.0.20230622:
  Successfully uninstalled snscrape-0.7.0.20230622
Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /tmp/pip-req-build-lgns3exv
  Running command git clone --filter=blob:none --quiet https://github.com/JustAnotherArchivist/snscrape.git /tmp/pip-req-build-lgns3exv
  Resolved https://github.com/JustAnotherArchivist/snscrape.git to commit 614d4c2029a62d348ca56598f87c425966aaec66
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (2.32.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (6.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from snscrape==0.7.0.20230622) (3.25.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape==0.7.0.20230622) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->snscrape==0.7.0.20230622) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->snscrape==0.7.0.20230622) (1.7.1)
Building wheels for collected packages: snscrape
  Building wheel for snscrape (pyproject.toml) ... done
  Created wheel for snscrape: filename=snscrape-0.7.0.20230622-py3-none-any.whl size=74851 sha256=c1a381e2d385c5f6981d36eec62344f986d41faf14f013eb6da25edb5120222a
  Stored in directory: /tmp/pip-ephem-wheel-cache-brpo8_u1/wheels/23/96/eb/f46ee85f779c8e28c7981ded4e8572bfa2bbe2c5bf20ecb4f4
Successfully built snscrape
Installing collected packages: snscrape
Successfully installed snscrape-0.7.0.20230622

In [ ]:
import tweepy
import pandas as pd
import time

In [ ]:
Bearer_Token="AAAAAAAAAAAAAAAAAAAAADnv8AEAAAAAG1rvIh8DpXEiqqi0uPtpU4aKZ68%3Dtjckaemd5f4ZLyrFuFGp3e8X3PbSKztCbHi2Q9j810eKUgd0sK"

In [ ]:
# calling api key
client =tweepy.Client(bearer_token=Bearer_Token)

In [ ]:
# search query
query="(Iran war OR Iran attack OR Iran missile OR Iran Israel) lang:en -is.retweet -is:reply"

In [ ]:
# collect 1000 tweets in batches of 100
all_tweets=[]
next_token=None
print("Collecting tweets.../n")

while len(all_tweets)<1000:
  Response = client.search_recent_tweets(
      query=query,
      max_results=100,
      tweet_fields=["created_at","author","lang"],
      next_token=next_token
  )
  if Response.data:
    for tweet in Response.data:
      all_tweets.append(
          {
              "id":tweet.id,
              "date":tweet.created_at,
              "text":tweet.text,
              "author":tweet.author_id,
              "like_count":tweet.public_metrics["like_count"],
              "retweet_count":tweet.public_metrics["retweet_count"],
              "replies_count":tweet.public_metrics["reply_count"],

          }
      )
      # if more pages exites
      next_token=Response.meta.get("next_token") if Response.meta None
      if not next_token:
        break
      print(f"Collected {len(all_tweets)} tweets")
      time.sleep(1)

SyntaxError: expected 'else' after 'if' expression (3560342665.py, line 28)